INSERT INTO system_changelog (version, title, description, changes, category, created_at) VALUES
('3.0.0', 'Plataforma v3.0 — Evolução Completa', 'Atualização massiva com novos módulos, perfil v3, segurança Cloudflare e sistema de pontuação expandido.', 
'["Conselho 24/7: quadro Kanban para membros pedirem ajuda e receberem respostas pontuadas (5 pts/resposta, +5 pts melhor resposta)",
"Cases de Negócio: registro de cases no perfil com slider, pontuação de 15 pts (autor) e 20 pts (indicador)",
"Perfil v3: novos campos (O que faço, Cliente ideal, Como me indicar, Tags), gerador de Pitch por IA",
"Cloudflare Turnstile: proteção anti-bot no cadastro de convidados com verificação via Edge Function",
"Cloudflare Web Analytics: monitoramento de Core Web Vitals e métricas de visitantes",
"Papéis Admin/Facilitador: visão gerencial sem pontuação, acesso a relatórios globais",
"Mobile BottomNav: atalhos por papel (Membro, Admin, Facilitador) com cara de app",
"Membros + Grupos unificados: cards com selo de facilitador e cor diferenciada",
"Feed de Atividades: feed completo com filtros por grupo, detalhes de cada ação",
"Indicações com status: Frio/Morno/Quente com cores visuais",
"Gestão de Convidados por Encontro: lista de convidados separada por evento",
"Eventos ordenados por data com destaque 7 dias antes",
"Controle de convites: exclusão manual e expiração corrigida",
"Histórico de pontos funcional no perfil próprio e de outros membros",
"Admin: CRUD completo de registros, KPIs por grupo, relatórios globais",
"Estatísticas expandidas: filtros por grupo e período, métricas de Conselho e Cases",
"Sistema de pontuação atualizado com 10 atividades pontuáveis",
"Documentação técnica, fluxos e guias de uso atualizados para v3.0"]'::jsonb,
'release', NOW());