// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Proxy URL for edge-cached API requests (optional, falls back to direct Supabase)
export const PROXY_URL = import.meta.env.VITE_PROXY_URL || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Read-only Supabase client that routes through the Cloudflare Worker proxy
 * for edge-cached responses. Falls back to the regular client if PROXY_URL is not set.
 * Use ONLY for read operations on cacheable endpoints (profiles, teams, meetings, etc.)
 */
export const supabaseReadOnly = PROXY_URL
  ? createClient<Database>(PROXY_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : supabase;