// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vyfkddcbmwlwldaorxzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZmtkZGNibXdsd2xkYW9yeHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwODUzMTYsImV4cCI6MjA4MDY2MTMxNn0.NXJ12zhicB1iw3O18zxVaDX34OWa3BOEpaI2fp8B7-s";

// Proxy URL for edge-cached API requests (optional, falls back to direct Supabase)
export const PROXY_URL = import.meta.env.VITE_PROXY_URL || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Read-only Supabase client alias.
 * Previously pointed to a separate Cloudflare Worker proxy client, but that approach
 * broke RLS because the second client didn't share the auth session.
 * Now it's a direct alias — the proxy should be configured at infrastructure level
 * (e.g., VITE_SUPABASE_URL pointing to the Worker) rather than as a second client.
 */
export const supabaseReadOnly = supabase;